version: '3.4'

services:
  server:
    build: server
    command: flask run
    volumes:
      - ./data:/server/data
    environment:
      - FLASK_APP=server.py
      - FLASK_RUN_HOST=0.0.0.0
    ports:
      - 6969:5000
      
  client:
    build: client
    command: python ./client.py
    depends_on:
      - server


